on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    uses: gardenlinux/package-build/.github/workflows/build.yml@main
    with:
      release: ${{ github.ref == 'refs/heads/main' }}
      build_dep: |
        gardenlinux/bp-package-nghttp3 1.6.0-1gl0
        gardenlinux/bp-package-ngtcp2 1.9.1-1gl0
 
